# Generated by Django 5.0.6 on 2024-12-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('男性', '男性'), ('女性', '女性'), ('その他', 'その他')], max_length=10)),
                ('age', models.CharField(choices=[('10代', '10代'), ('20代', '20代'), ('30代', '30代'), ('40代', '40代'), ('50代', '50代'), ('60代以上', '60代以上')], max_length=10)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名前')),
                ('start_time', models.DateTimeField(verbose_name='開始時間')),
                ('end_time', models.DateTimeField(verbose_name='終了時間')),
                ('treatment_location', models.CharField(choices=[('出張', '出張'), ('下津カフェMOCA', '下津カフェMOCA')], max_length=50, verbose_name='施術場所')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='電話番号')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='メールアドレス')),
                ('email_confirm', models.EmailField(blank=True, max_length=254, null=True, verbose_name='メールアドレス(確認)')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='コメント')),
            ],
        ),
    ]
