# Generated by Django 5.0.6 on 2024-08-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0003_event_description_event_end_time_alter_event_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名前')),
                ('start_time', models.DateTimeField(verbose_name='開始時間')),
                ('end_time', models.DateTimeField(verbose_name='終了時間')),
                ('treatment_location', models.CharField(choices=[('onsite', '出張'), ('moca', '下津カフェMOCA')], max_length=50, verbose_name='施術場所')),
            ],
        ),
    ]
