# Generated by Django 5.0.6 on 2024-08-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0004_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
