# Generated by Django 5.0.6 on 2024-08-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0006_alter_request_email_alter_request_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='email_confirm',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name=' メールアドレス(確認)'),
        ),
        migrations.AlterField(
            model_name='request',
            name='email',
            field=models.EmailField(blank=True, help_text='メールアドレスをもう一度入力してください', max_length=254, null=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='request',
            name='name',
            field=models.CharField(max_length=255, verbose_name='\u3000\u3000名前'),
        ),
        migrations.AlterField(
            model_name='request',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='電話番号'),
        ),
    ]
