# Generated by Django 5.0.6 on 2024-10-09 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0008_notice_alter_request_email_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateField(),
        ),
    ]
