# Generated by Django 5.0.6 on 2024-11-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0009_alter_notice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='コメント'),
        ),
        migrations.AlterField(
            model_name='request',
            name='name',
            field=models.CharField(max_length=255, verbose_name='名前'),
        ),
    ]
