# Generated by Django 5.0.6 on 2024-11-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0010_request_comment_alter_request_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='症状について、できる限り詳細にお書きください'),
        ),
    ]
