# Generated by Django 5.0.6 on 2024-11-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0011_alter_request_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='コメント'),
        ),
    ]
